name: shared
description: Shared models, services, and widgets for All-Serve
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  
  # Storage & Security
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # HTTP & File Upload
  http: ^1.1.0
  file_picker: ^10.3.2
  
  # Location
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  
  # UI
  google_fonts: ^6.3.1
  cached_network_image: ^3.3.1
  
  # State Management
  provider: ^6.1.1
  
  # Notifications
  flutter_local_notifications: ^19.4.1
  permission_handler: ^12.0.1
  
  # Utilities
  intl: ^0.20.2
  path: ^1.9.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0