// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1LzDsU_v77H1GuuXKjYrkS1ZoFXhbZU8',
    appId: '1:1067837770200:web:458fc866cc0602dfe40aad',
    messagingSenderId: '1067837770200',
    projectId: 'all-serve',
    authDomain: 'all-serve.firebaseapp.com',
    storageBucket: 'all-serve.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1LzDsU_v77H1GuuXKjYrkS1ZoFXhbZU8',
    appId: '1:1067837770200:android:458fc866cc0602dfe40aad',
    messagingSenderId: '1067837770200',
    projectId: 'all-serve',
    storageBucket: 'all-serve.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1LzDsU_v77H1GuuXKjYrkS1ZoFXhbZU8',
    appId: '1:1067837770200:ios:458fc866cc0602dfe40aad',
    messagingSenderId: '1067837770200',
    projectId: 'all-serve',
    storageBucket: 'all-serve.firebasestorage.app',
    iosBundleId: 'com.maluDev.allServer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1LzDsU_v77H1GuuXKjYrkS1ZoFXhbZU8',
    appId: '1:1067837770200:macos:458fc866cc0602dfe40aad',
    messagingSenderId: '1067837770200',
    projectId: 'all-serve',
    storageBucket: 'all-serve.firebasestorage.app',
    iosBundleId: 'com.maluDev.allServer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1LzDsU_v77H1GuuXKjYrkS1ZoFXhbZU8',
    appId: '1:1067837770200:windows:458fc866cc0602dfe40aad',
    messagingSenderId: '1067837770200',
    projectId: 'all-serve',
    storageBucket: 'all-serve.firebasestorage.app',
  );
}
